### PR TITLE
Update to swift 4

### PR DESCRIPTION
**Pull request by onmyway133**
⚠️ Breaking changes ⚠️ 

- Update swift version to swift 4
- Remove unused files
- Update method names

### CODE REVIEW

**Comment by vadymmarkov** [comment]
@onmyway133 I see you've removed a lot of code. Do you think we don't need it anymore?

**Comment by onmyway133** [comment]
@vadymmarkov to answer your question

- Remove some `keyboard handlers` as the only useful is the `CustomKeyboardHandler`
- Remove `swizzler` as it is not recommended
- Remove `some string extensions` are they are opinionated.
- Remove `custom operators` as it is not recommended
- Remove `dispatch queue` as they are very thin wrappers around `DispatchQueue`, and does not offer much advantages

**Comment by vadymmarkov** [comment]
What do you think @zenangst

**Comment by zenangst** [comment]
I'd rather not removing anything in this PR has it is beyond the scope for the PR. Either it is a PR that removes functionality or it is a Swift 4 migration. When it comes to removal, I'd open discussions about it instead of just removing it. Justify why it is redundant and deserves to be removed.

**Comment by zenangst** [comment]
Basically, the removal of all these things will be masked by the fact that it happened in a version update migration.

**Comment by onmyway133** [comment]
@zenangst right, I will close this, and match PRs in smaller batches, so that we can discuss separately

**Pull request closed without merging**
