### PR TITLE
Feature/split string extension

### PR DESCRIPTION
**Pull request by zenangst**
With this PR, you can easily split up `String`’s into multiple parts by calling `split()`.

```swift
"root/path/file".split("/")
// ["root", "path", "file"]
```

### CODE REVIEW

**Comment by zenangst** [comment]
@hyperoslo/ios merge conflicts fixed ^^

**Comment by vadymmarkov** [comment]
@zenangst Is it better than `componentsSeparatedByString`?

**Comment by zenangst** [comment]
Haven't checked performance, I probably should ;)

**Comment by zenangst** [comment]
Did some testing and doing;

```swift
func split(delimiter: Character) -> [String] {
  return characters
    .split { $0 == delimiter }
    .map(String.init)
}
```

Is a lot slower than `componentsSeparatedByString` :)

```swift
    let testString = "root/path/file"

    let testA = UnitTesting.measure {
      for _ in 0...1000 {
        _ = testString.split("/")
      }
    }

    let testB = UnitTesting.measure {
      for _ in 0...1000 {
        _ = testString.componentsSeparatedByString("/")
      }
    }

    XCTAssertTrue(testA < testB)
```
### Results
```
testA: 0.0298243
testB: 0.0109432
```

**Comment by zenangst** [comment]
@vadymmarkov changed the implementation to use `componentsSeparatedByString` now ;)

**Comment by zenangst** [comment]
@vadymmarkov bump ;)

**Comment by vadymmarkov** [comment]
@zenangst :+1:

**Pull request merged**
