### PR TITLE
Handling gesture the easy way

### PR DESCRIPTION
**Pull request by onmyway133**
This make handling gesture more easily, with block

It works this way
- ViewController -strong-> GestureSense -strong-> Target -strong-> handler block
- UIGestureRecognizer -weak-> Target
- It won't attach the same kind of gesture twice

``` swift
let sense = GestureSense()
let view = UIView()

sense.tap(view) { gr in

}

sense.pan(view) { gr in

}

sense.pan(view) { gr in

}
```

### CODE REVIEW

**Comment by vadymmarkov** [comment]
This is great @onmyway133, but what I'm kinda afraid of is that Sugar getting bigger and bigger as being mentioned by @zenangst.

**Comment by zenangst** [comment]
I think we need to adress this is a good way, maybe splitting it out in to separate repos where it makes sense and then starting to mark things as `deprecated` and then remove extract and remove bits and pieces from the Sugar core.

Arguably, we need to find a good middle ground to what goes into `Sugar` and what does not.

I think this could be merge into `master` and then discuss this further in an issue on the repo, what do you guys think? @hyperoslo/ios @aashishdhawan.

**Comment by vadymmarkov** [comment]
@zenangst Sounds like a plan.

**Comment by RamonGilabert** [comment]
Kind of agree. Problem is that I think we are starting to confuse convenience with just a sugar, in my opinion where the latter one is something that fixes some tedious work you have to do over and over (dispatch, localize, iPhone size, etc.), the first one is just something that is nifty and looks better than what Apple provides. That one I think should go to another pod. And this PR kind of goes into that one.

**Comment by zenangst** [comment]
Made an issue for discussion here -> https://github.com/hyperoslo/Sugar/issues/79

**Comment by vadymmarkov** [comment]
@zenangst @RamonGilabert We haven't agreed on something there https://github.com/hyperoslo/Sugar/issues/79 but @onmyway133 has done an awesome job, so it's worth merging anyway I guess.

**Comment by onmyway133** [comment]
@vadymmarkov I think we can move this to another repo?

**Comment by vadymmarkov** [comment]
@onmyway133 It's what I would do, yes. But depends on what we decide with Sugar future.

**Comment by RamonGilabert** [comment]
Sugar might turn its direction now with the sugars that  has already put in Swift 3. Maybe now the solution is do more stuff like this and not sugars?

**Comment by Vaberer** [comment]
The idea of using gestures like this is more than super convenient. I would extend Sugar as much as possible also with String, Array etc convenient methods and it's only up to the developer if he uses some of the functions. 

For me, the most safe approach is to fork a repo and add methods to the library which are useful for me and everything in one place

**Comment by onmyway133** [comment]
I think I will close this for now 😄

**Pull request closed without merging**
