### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by onmyway133**
- Mention OS X
- Mention date construction
- Mention Keyboard handling

Also this uses https://atom.io/packages/markdown-toc to generate TOC

### CODE REVIEW

**Comment by RamonGilabert** [comment]
jajajaja nice.

**Comment by onmyway133** [comment]
so cool reviewer @RamonGilabert what do you think 😬

**Comment by zenangst** [comment]
Oh, it worked! 😁

**Comment by vadymmarkov** [comment]
This is great! 😄

**Pull request merged**
