### PR TITLE
Add KeyboardObserver and Handler to handle keyboard events

### PR DESCRIPTION
**Pull request by onmyway133**
- Observer keyboard will show and will hide events
- Currently support handler for basic animation, custom block, scrollview insets, layout constraint
- Add new handler by conforming to KeyboardHandler protocol

### CODE REVIEW

**Comment by onmyway133** [comment]
@zenangst I think it's good for review now 🐻

**Comment by zenangst** [comment]
@onmyway133 🚀

**Comment by onmyway133** [comment]
@zenangst 🎉  we have more things now than stated in the readme

**Comment by zenangst** [comment]
@onmyway133 feel free to update the README 😁

**Comment by onmyway133** [comment]
@zenangst it is https://github.com/hyperoslo/Sugar/pull/77 😬

**Pull request merged**
