### PR TITLE
Fix the use of insets

### PR DESCRIPTION
**Pull request by onmyway133**
Trailing and bottom anchors should be using negative, that's what we want :)

### CODE REVIEW

**Comment by vadymmarkov** [comment]
It kinda makes sense, but I'm not sure. It's a super breaking change for me.

**Comment by onmyway133** [comment]
@vadymmarkov yeah I see. But then we should have another struct instead of `UIEdgeInsets`, the behaviour here is different from what we know from `CGRect`

**Comment by onmyway133** [comment]
Or we can have insets like

```swift
extension UIEdgeInsets {

  init(constraintInsets value: CGFloat) {
    top = value
    left = value
    bottom = -value
    right = -value
  }
}
```

**Comment by zenangst** [comment]
@onmyway133 so with this change, you would never set negative values on your constraints?

**Comment by onmyway133** [comment]
@zenangst I think for using `insets` like this, most of the cases, users expect it to behave like `insets` in `CGRect`, like an inner padding. So we try to help them by proactively adding `-` for them. But I'm biased on this too

**Comment by zenangst** [comment]
@onmyway133 that all depends, the normal case for adding constraints is to actually do `-` when constraining it to the bottom with a bit of margin isn't it?

**Comment by onmyway133** [comment]
@zenangst you're right. But this is a helper, so it tries to help :)

**Comment by zenangst** [comment]
@onmyway133 remember the convenience methods in `Spots`? They don't always help if you have to question how they work 😁

**Comment by zenangst** [comment]
I do agree that constraints are backwards to begin with, but using a wrapper for constraints, I would assume that they would still use the same logic. Just my 50 cents :)

**Comment by onmyway133** [comment]
@zenangst Right. I think I will close this for now. It is a bit too clever

**Pull request closed without merging**
