### PR TITLE
UIView extension for UINib initializer wrapper method.

### PR DESCRIPTION
**Pull request by aksswami**
NSTimeInterval utility method and properties added.

### CODE REVIEW

**Comment by aksswami** [comment]
@zenangst Any comments, review?

**Comment by onmyway133** [comment]
@aksswami thanks, perhaps the title should be changed "UIView extension for UINib initializer wrapper method" 😄

**Comment by aksswami** [comment]
@onmyway133 Thanks

**Comment by onmyway133** [comment]
@aksswami Hi, thanks for your PR 💪 Your idea has been integrated into `Sugar` and is in Swift 3 now. Closing this for now

**Pull request closed without merging**
